version = 0.1

[default.deploy.parameters]
stack_name = "Notify-RDS-Cluster-Failover-reader-write-instance-swapping"
resolve_s3 = true
s3_prefix = "Notify-RDS-Cluster-Failover-reader-write-instance-swapping"
region = "us-east-2"
profile = "gwre-shared-services"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
