AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: RDS Failover Notification System

Resources:
  RDSEventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Trigger when RDS failover events occur"
      EventPattern:
        source:
          - "aws.rds"
        detail-type:
          - "RDS DB Instance Event"
        detail:
          EventCategories:
            - "failover"
      State: "ENABLED"
      Targets:
        - Arn: !GetAtt RDSFailoverNotificationFunction.Arn
          Id: "RDSFailoverLambdaTarget"

  RDSFailoverNotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/app.py
      Handler: app.lambda_handler
      Runtime: python3.13
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !Ref NotificationTopic
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref NotificationTopic
      Events:
        CloudWatchEvent:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - "aws.rds"
              detail-type:
                - "RDS DB Instance Event"
              detail:
                EventCategories:
                  - "failover"

  NotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: "RDS Failover Notifications"
      Subscription:
        - Protocol: "email"
          Endpoint: "selimcse98@gmail.com"
        - Protocol: "email"
          Endpoint: "mmiah@guidewire.com"
        - Protocol: "sms"
          Endpoint: "0469214498"
        - Protocol: "sms"
          Endpoint: "0469218933"

Outputs:
  RDSEventRuleArn:
    Description: "EventBridge Rule ARN"
    Value: !GetAtt RDSEventRule.Arn
  NotificationTopicArn:
    Description: "SNS Topic ARN"
    Value: !Ref NotificationTopic
  LambdaFunctionArn:
    Description: "Lambda Function ARN"
    Value: !GetAtt RDSFailoverNotificationFunction.Arn